version: '2'

services:
  ikmongo:
    container_name: ikmongo
    image: mongo
    volumes:
      - /v/mongo:/data/db
    ports:
      - "27017:27017"
    restart: always

  iksirene:
    build: .
    image: yieloo/sirene
    container_name: iksirene
    environment:
      - DB_HOST=ikmongo
      - DB_NAME=sirene
    ports:
      - "8080:3000"
    links:
      - ikmongo
    restart: always